---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.16.14

dependencies:
  galaxy: requirements.yml

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: /home/eames/.ssh/ansible/ansible.cfg
    dest: configs

additional_build_steps:
  prepend_base:
    # Make ansible dir becauser ADD ~/.ansible.cfg not working
    - RUN mkdir -p /etc/ansible/
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
