---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.17.14

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_base:
     - RUN microdnf install -y wget tar  # Ensure wget is available
     - RUN wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64.tar.gz -O - | tar xz && mv yq_linux_amd64 /usr/bin/yq
