---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.17.14

dependencies:
  galaxy:
    collections:
      - name: cohesity.dataprotect
        version: "1.4.2"
      - name: ansible.utils
        version: "6.0.0"

options:
  package_manager_path: /usr/bin/microdnf
